version: '3.3'
services:
    broker :
        image : eclipse-mosquitto
        hostname : broker
        container_name : broker
        expose :
            - "1883"
        ports :
            - 6502:1883
        volumes :
            - /home/diot/Desktop/Vishwajit/Q5/mosquitto.conf:/mosquitto/config/mosquitto.conf
    subscriberexam :
        build : ./subscriber
        container_name : subscriberexam
        hostname : sub
        depends_on :
            - broker